# 의사결정트리 시각화하기

## 목표

1. Import **Dataset**
2. Train a **Classifier**
3. Predict **Label** for new data
4. Visualize the **Tree**

In [8]:
import numpy as np
from sklearn.datasets import load_iris

# 1. Import Dataset

In [9]:
iris = load_iris()

In [10]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [11]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [12]:
iris.data[0]

array([5.1, 3.5, 1.4, 0.2])

In [13]:
iris.target[0]
# 0: 'setosa'

0

## Split Data

- Dataset을 **Training Data**와 **Testing Data**로 split한다.
  + Testing Data : classifier의 정확도를 test하기 위한 examples

In [15]:
test_idx = [0, 50, 100]

# training data
train_target = np.delete(iris.target, test_idx)
train_data = np.delete(iris.data, test_idx, axis=0)

# testing data
test_target = iris.target[test_idx]
test_data = iris.data[test_idx]

# 2. Train a Classifier

In [16]:
from sklearn import tree

In [17]:
clf = tree.DecisionTreeClassifier()
clf.fit(train_data, train_target)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

# 3. Predict Label for new data

In [18]:
clf.predict(test_data)

array([0, 1, 2])

In [19]:
test_target

array([0, 1, 2])

# 4. Visualize the Tree

![](http://lijiancheng0614.github.io/scikit-learn/_images/iris.svg)

- 좋은 features가 제공될수록 좋은 Tree 모형이 만들어진다.